### PR TITLE
I added a parameter in the setup file called 'stdfile' which currently p...

### PR DESCRIPTION
**Pull request by knutago**
...oints to /home/smash/SMASH/standards.txt and a code snippet in photred_rename to match the object field against the standard fields in that file:

  ; Check for standards against standard file
  stdfile=readpar(setup,'STDFILE')
  if (FILE_TEST(stdfile) eq 1) then begin
    readcol,stdfile,stdname,stdra,stdec,f='a,a,a',/silent
    stdcheck = max(stregex(stdname,object2,/fold_case,/boolean))

and:

  ; Standard star field
  if (sa98 eq 1) or (sa110 eq 1) or (sa114 eq 1) or $
     (n3680 eq 1) or (stdcheck eq 1) then stdarr[i] = 1

### CODE REVIEW

**Comment by knutago** [comment]
Cool, my first pull request!

**Comment by dnidever** [comment]
Mine, too!  It worked smoothly.

On Mon, Apr 27, 2015 at 2:41 PM, knutago notifications@github.com wrote:

> Cool, my first pull request!
> 
> > On Apr 27, 2015, at 7:14 AM, dnidever notifications@github.com wrote:
> > 
> > Merged #1 https://github.com/dnidever/PHOTRED/pull/1.
> > 
> > —
> > Reply to this email directly or view it on GitHub <
> > https://github.com/dnidever/PHOTRED/pull/1#event-290915860>.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/dnidever/PHOTRED/pull/1#issuecomment-96775516.

## 

---

David Lee Nidever              University of Michigan, Ann Arbor
McLaughlin Fellow              Department of Astronomy
dnidever@umich.edu         http://www.astro.lsa.umich.edu/~dnidever

**Comment by dnidever** [comment]
But now I can't update the PHOTRED code in thing from the PHOTRED repository
because we are on the "knut" branch.  I think we should keep the main code
for
thing on the "master" branch.

On Mon, Apr 27, 2015 at 2:47 PM, David Nidever dnidever@umich.edu wrote:

> Mine, too!  It worked smoothly.
> 
> On Mon, Apr 27, 2015 at 2:41 PM, knutago notifications@github.com wrote:
> 
> > Cool, my first pull request!
> > 
> > > On Apr 27, 2015, at 7:14 AM, dnidever notifications@github.com wrote:
> > > 
> > > Merged #1 https://github.com/dnidever/PHOTRED/pull/1.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub <
> > > https://github.com/dnidever/PHOTRED/pull/1#event-290915860>.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/dnidever/PHOTRED/pull/1#issuecomment-96775516.
> 
> ## 
> 
> ---
> 
> David Lee Nidever              University of Michigan, Ann Arbor
> McLaughlin Fellow              Department of Astronomy
> dnidever@umich.edu         http://www.astro.lsa.umich.edu/~dnidever

## 

---

David Lee Nidever              University of Michigan, Ann Arbor
McLaughlin Fellow              Department of Astronomy
dnidever@umich.edu         http://www.astro.lsa.umich.edu/~dnidever

**Comment by knutago** [comment]
Just need to say “git checkout master” in the PHOTRED directory.

**Comment by knutago** [comment]
Hi David,

```
Just tried checking out master in the PHOTRED directory, and it’s having some problems.  Are you fiddling with things?

Knut
```

**Comment by dnidever** [comment]
Yes.  There was a crash and so I was checking/modifying things.
I made the necessary changes on my laptop and pushed them to
github.  I was trying to update the software on "thing" when I got
errors.

By the way, I got an error saying that "root" was full.  I'm not sure what
that's about.  Do you know?

On Tue, Apr 28, 2015 at 12:01 PM, knutago notifications@github.com wrote:

> Hi David,
> 
> Just tried checking out master in the PHOTRED directory, and it’s having
> some problems. Are you fiddling with things?
> 
> Knut
> 
> > On Apr 28, 2015, at 7:39 AM, dnidever notifications@github.com wrote:
> > 
> > But now I can't update the PHOTRED code in thing from the PHOTRED
> > repository
> > because we are on the "knut" branch. I think we should keep the main code
> > for
> > thing on the "master" branch.
> > 
> > On Mon, Apr 27, 2015 at 2:47 PM, David Nidever dnidever@umich.edu
> > wrote:
> > 
> > > Mine, too! It worked smoothly.
> > > 
> > > On Mon, Apr 27, 2015 at 2:41 PM, knutago notifications@github.com
> > > wrote:
> > > 
> > > > Cool, my first pull request!
> > > > 
> > > > > On Apr 27, 2015, at 7:14 AM, dnidever notifications@github.com
> > > > > wrote:
> > > > > 
> > > > > Merged #1 https://github.com/dnidever/PHOTRED/pull/1.
> > > > > 
> > > > > —
> > > > > Reply to this email directly or view it on GitHub <
> > > > > https://github.com/dnidever/PHOTRED/pull/1#event-290915860>.
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > https://github.com/dnidever/PHOTRED/pull/1#issuecomment-96775516.
> > > 
> > > ## 
> > > 
> > > ---
> > > 
> > > David Lee Nidever University of Michigan, Ann Arbor
> > > McLaughlin Fellow Department of Astronomy
> > > dnidever@umich.edu http://www.astro.lsa.umich.edu/~dnidever
> > 
> > ## 
> > 
> > ---
> > 
> > David Lee Nidever University of Michigan, Ann Arbor
> > McLaughlin Fellow Department of Astronomy
> > dnidever@umich.edu http://www.astro.lsa.umich.edu/~dnidever
> > —
> > Reply to this email directly or view it on GitHub <
> > https://github.com/dnidever/PHOTRED/pull/1#issuecomment-97087330>.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/dnidever/PHOTRED/pull/1#issuecomment-97118829.

## 

---

David Lee Nidever              University of Michigan, Ann Arbor
McLaughlin Fellow              Department of Astronomy
dnidever@umich.edu         http://www.astro.lsa.umich.edu/~dnidever

**Comment by dnidever** [comment]
I'm trying to copy files there by hand but I'm getting and error.
Not sure what's going on.

On Tue, Apr 28, 2015 at 12:46 PM, David Nidever dnidever@umich.edu wrote:

> Yes.  There was a crash and so I was checking/modifying things.
> I made the necessary changes on my laptop and pushed them to
> github.  I was trying to update the software on "thing" when I got
> errors.
> 
> By the way, I got an error saying that "root" was full.  I'm not sure what
> that's about.  Do you know?
> 
> On Tue, Apr 28, 2015 at 12:01 PM, knutago notifications@github.com
> wrote:
> 
> > Hi David,
> > 
> > Just tried checking out master in the PHOTRED directory, and it’s having
> > some problems. Are you fiddling with things?
> > 
> > Knut
> > 
> > > On Apr 28, 2015, at 7:39 AM, dnidever notifications@github.com wrote:
> > > 
> > > But now I can't update the PHOTRED code in thing from the PHOTRED
> > > repository
> > > because we are on the "knut" branch. I think we should keep the main
> > > code
> > > for
> > > thing on the "master" branch.
> > > 
> > > On Mon, Apr 27, 2015 at 2:47 PM, David Nidever dnidever@umich.edu
> > > wrote:
> > > 
> > > > Mine, too! It worked smoothly.
> > > > 
> > > > On Mon, Apr 27, 2015 at 2:41 PM, knutago notifications@github.com
> > > > wrote:
> > > > 
> > > > > Cool, my first pull request!
> > > > > 
> > > > > > On Apr 27, 2015, at 7:14 AM, dnidever notifications@github.com
> > > > > > wrote:
> > > > > > 
> > > > > > Merged #1 https://github.com/dnidever/PHOTRED/pull/1.
> > > > > > 
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub <
> > > > > > https://github.com/dnidever/PHOTRED/pull/1#event-290915860>.
> > > > > 
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > https://github.com/dnidever/PHOTRED/pull/1#issuecomment-96775516.
> > > > 
> > > > ## 
> > > > 
> > > > ---
> > > > 
> > > > David Lee Nidever University of Michigan, Ann Arbor
> > > > McLaughlin Fellow Department of Astronomy
> > > > dnidever@umich.edu http://www.astro.lsa.umich.edu/~dnidever
> > > 
> > > ## 
> > > 
> > > ---
> > > 
> > > David Lee Nidever University of Michigan, Ann Arbor
> > > McLaughlin Fellow Department of Astronomy
> > > dnidever@umich.edu http://www.astro.lsa.umich.edu/~dnidever
> > > —
> > > Reply to this email directly or view it on GitHub <
> > > https://github.com/dnidever/PHOTRED/pull/1#issuecomment-97087330>.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/dnidever/PHOTRED/pull/1#issuecomment-97118829.
> 
> ## 
> 
> ---
> 
> David Lee Nidever              University of Michigan, Ann Arbor
> McLaughlin Fellow              Department of Astronomy
> dnidever@umich.edu         http://www.astro.lsa.umich.edu/~dnidever

## 

---

David Lee Nidever              University of Michigan, Ann Arbor
McLaughlin Fellow              Department of Astronomy
dnidever@umich.edu         http://www.astro.lsa.umich.edu/~dnidever

**Comment by knutago** [comment]
I think that means that the boot disk is full, wonder why that is?

So for doing work on github, when modifying the code it helps to create a branch and then when the work is done, merging that branch back to master.  There’s some good docs on github at the github site.  WIll probably help you get up to speed with the LSST DM Stack!

If the repository on thing is screwed up, we can always clone a new version of master from github…but are there changes that you’ve made that are not on github?

**Comment by knutago** [comment]
If you pause, I’ll see if I can fix it…

**Comment by knutago** [comment]
Ok, have a look now, is it up to date?  I had to use sudo to force a checkout to master, if your git repository is up to date it might be good to do a fresh clone as user smash...

**Comment by dnidever** [comment]
Can you change ownership of the files to "smash"?  Some of them are "root"
and I can't modify them.  I need to put in a stop of figure out a daomaster
problem.

On Tue, Apr 28, 2015 at 1:16 PM, knutago notifications@github.com wrote:

> Ok, have a look now, is it up to date? I had to use sudo to force a
> checkout to master, if your git repository is up to date it might be good
> to do a fresh clone as user smash...
> 
> > On Apr 28, 2015, at 9:51 AM, dnidever notifications@github.com wrote:
> > 
> > I'm trying to copy files there by hand but I'm getting and error.
> > Not sure what's going on.
> > 
> > On Tue, Apr 28, 2015 at 12:46 PM, David Nidever dnidever@umich.edu
> > wrote:
> > 
> > > Yes. There was a crash and so I was checking/modifying things.
> > > I made the necessary changes on my laptop and pushed them to
> > > github. I was trying to update the software on "thing" when I got
> > > errors.
> > > 
> > > By the way, I got an error saying that "root" was full. I'm not sure
> > > what
> > > that's about. Do you know?
> > > 
> > > On Tue, Apr 28, 2015 at 12:01 PM, knutago notifications@github.com
> > > wrote:
> > > 
> > > > Hi David,
> > > > 
> > > > Just tried checking out master in the PHOTRED directory, and it’s
> > > > having
> > > > some problems. Are you fiddling with things?
> > > > 
> > > > Knut
> > > > 
> > > > > On Apr 28, 2015, at 7:39 AM, dnidever notifications@github.com
> > > > > wrote:
> > > > > 
> > > > > But now I can't update the PHOTRED code in thing from the PHOTRED
> > > > > repository
> > > > > because we are on the "knut" branch. I think we should keep the main
> > > > > code
> > > > > for
> > > > > thing on the "master" branch.
> > > > > 
> > > > > On Mon, Apr 27, 2015 at 2:47 PM, David Nidever dnidever@umich.edu
> > > > > wrote:
> > > > > 
> > > > > > Mine, too! It worked smoothly.
> > > > > > 
> > > > > > On Mon, Apr 27, 2015 at 2:41 PM, knutago <
> > > > > > notifications@github.com>
> > > > > > wrote:
> > > > > > 
> > > > > > > Cool, my first pull request!
> > > > > > > 
> > > > > > > > On Apr 27, 2015, at 7:14 AM, dnidever <
> > > > > > > > notifications@github.com>
> > > > > > > > wrote:
> > > > > > > > 
> > > > > > > > Merged #1 https://github.com/dnidever/PHOTRED/pull/1.
> > > > > > > > 
> > > > > > > > —
> > > > > > > > Reply to this email directly or view it on GitHub <
> > > > > > > > https://github.com/dnidever/PHOTRED/pull/1#event-290915860>.
> > > > > > > 
> > > > > > > —
> > > > > > > Reply to this email directly or view it on GitHub
> > > > > > > <
> > > > > > > https://github.com/dnidever/PHOTRED/pull/1#issuecomment-96775516>.
> > > > > > 
> > > > > > ## 
> > > > > > 
> > > > > > ---
> > > > > > 
> > > > > > David Lee Nidever University of Michigan, Ann Arbor
> > > > > > McLaughlin Fellow Department of Astronomy
> > > > > > dnidever@umich.edu http://www.astro.lsa.umich.edu/~dnidever
> > > > > 
> > > > > ## 
> > > > > 
> > > > > ---
> > > > > 
> > > > > David Lee Nidever University of Michigan, Ann Arbor
> > > > > McLaughlin Fellow Department of Astronomy
> > > > > dnidever@umich.edu http://www.astro.lsa.umich.edu/~dnidever
> > > > > —
> > > > > Reply to this email directly or view it on GitHub <
> > > > > https://github.com/dnidever/PHOTRED/pull/1#issuecomment-97087330>.
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > https://github.com/dnidever/PHOTRED/pull/1#issuecomment-97118829.
> > > 
> > > ## 
> > > 
> > > ---
> > > 
> > > David Lee Nidever University of Michigan, Ann Arbor
> > > McLaughlin Fellow Department of Astronomy
> > > dnidever@umich.edu http://www.astro.lsa.umich.edu/~dnidever
> > 
> > ## 
> > 
> > ---
> > 
> > David Lee Nidever University of Michigan, Ann Arbor
> > McLaughlin Fellow Department of Astronomy
> > dnidever@umich.edu http://www.astro.lsa.umich.edu/~dnidever
> > —
> > Reply to this email directly or view it on GitHub <
> > https://github.com/dnidever/PHOTRED/pull/1#issuecomment-97135230>.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/dnidever/PHOTRED/pull/1#issuecomment-97141594.

## 

---

David Lee Nidever              University of Michigan, Ann Arbor
McLaughlin Fellow              Department of Astronomy
dnidever@umich.edu         http://www.astro.lsa.umich.edu/~dnidever

**Comment by knutago** [comment]
Thought I had fixed that...

**Comment by dnidever** [comment]
Six of the files are still owned by root.  Those are the ones that were
recently modified.

On Tue, Apr 28, 2015 at 1:49 PM, knutago notifications@github.com wrote:

> Thought I had fixed that...
> 
> > On Apr 28, 2015, at 10:47 AM, dnidever notifications@github.com wrote:
> > 
> > Can you change ownership of the files to "smash"? Some of them are "root"
> > and I can't modify them. I need to put in a stop of figure out a
> > daomaster
> > problem.
> > 
> > On Tue, Apr 28, 2015 at 1:16 PM, knutago notifications@github.com
> > wrote:
> > 
> > > Ok, have a look now, is it up to date? I had to use sudo to force a
> > > checkout to master, if your git repository is up to date it might be
> > > good
> > > to do a fresh clone as user smash...
> > > 
> > > > On Apr 28, 2015, at 9:51 AM, dnidever notifications@github.com
> > > > wrote:
> > > > 
> > > > I'm trying to copy files there by hand but I'm getting and error.
> > > > Not sure what's going on.
> > > > 
> > > > On Tue, Apr 28, 2015 at 12:46 PM, David Nidever dnidever@umich.edu
> > > > wrote:
> > > > 
> > > > > Yes. There was a crash and so I was checking/modifying things.
> > > > > I made the necessary changes on my laptop and pushed them to
> > > > > github. I was trying to update the software on "thing" when I got
> > > > > errors.
> > > > > 
> > > > > By the way, I got an error saying that "root" was full. I'm not
> > > > > sure
> > > > > what
> > > > > that's about. Do you know?
> > > > > 
> > > > > On Tue, Apr 28, 2015 at 12:01 PM, knutago <
> > > > > notifications@github.com>
> > > > > wrote:
> > > > > 
> > > > > > Hi David,
> > > > > > 
> > > > > > Just tried checking out master in the PHOTRED directory, and it’s
> > > > > > having
> > > > > > some problems. Are you fiddling with things?
> > > > > > 
> > > > > > Knut
> > > > > > 
> > > > > > > On Apr 28, 2015, at 7:39 AM, dnidever <notifications@github.com
> > > 
> > > wrote:
> > > 
> > > > > > > But now I can't update the PHOTRED code in thing from the
> > > > > > > PHOTRED
> > > > > > > repository
> > > > > > > because we are on the "knut" branch. I think we should keep the
> > > > > > > main
> > > > > > > code
> > > > > > > for
> > > > > > > thing on the "master" branch.
> > > > > > > 
> > > > > > > On Mon, Apr 27, 2015 at 2:47 PM, David Nidever <
> > > > > > > dnidever@umich.edu>
> > > > > > > wrote:
> > > > > > > 
> > > > > > > > Mine, too! It worked smoothly.
> > > > > > > > 
> > > > > > > > On Mon, Apr 27, 2015 at 2:41 PM, knutago <
> > > > > > > > notifications@github.com>
> > > > > > > > wrote:
> > > > > > > > 
> > > > > > > > > Cool, my first pull request!
> > > > > > > > > 
> > > > > > > > > > On Apr 27, 2015, at 7:14 AM, dnidever <
> > > > > > > > > > notifications@github.com>
> > > > > > > > > > wrote:
> > > > > > > > > > 
> > > > > > > > > > Merged #1 https://github.com/dnidever/PHOTRED/pull/1.
> > > > > > > > > > 
> > > > > > > > > > —
> > > > > > > > > > Reply to this email directly or view it on GitHub <
> > > > > > > > > > https://github.com/dnidever/PHOTRED/pull/1#event-290915860>.
> > > > > > > > > 
> > > > > > > > > —
> > > > > > > > > Reply to this email directly or view it on GitHub
> > > > > > > > > <
> > > > > > > > > https://github.com/dnidever/PHOTRED/pull/1#issuecomment-96775516>.
> > > > > > > > 
> > > > > > > > ## 
> > > > > > > > 
> > > > > > > > ---
> > > > > > > > 
> > > > > > > > David Lee Nidever University of Michigan, Ann Arbor
> > > > > > > > McLaughlin Fellow Department of Astronomy
> > > > > > > > dnidever@umich.edu http://www.astro.lsa.umich.edu/~dnidever
> > > > > > > 
> > > > > > > ## 
> > > > > > > 
> > > > > > > ---
> > > > > > > 
> > > > > > > David Lee Nidever University of Michigan, Ann Arbor
> > > > > > > McLaughlin Fellow Department of Astronomy
> > > > > > > dnidever@umich.edu http://www.astro.lsa.umich.edu/~dnidever
> > > > > > > —
> > > > > > > Reply to this email directly or view it on GitHub <
> > > > > > > https://github.com/dnidever/PHOTRED/pull/1#issuecomment-97087330
> > > > > > > .
> > > > > > 
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub
> > > > > > <https://github.com/dnidever/PHOTRED/pull/1#issuecomment-97118829
> > > > > > .
> > > > > 
> > > > > ## 
> > > > > 
> > > > > ---
> > > > > 
> > > > > David Lee Nidever University of Michigan, Ann Arbor
> > > > > McLaughlin Fellow Department of Astronomy
> > > > > dnidever@umich.edu http://www.astro.lsa.umich.edu/~dnidever
> > > > 
> > > > ## 
> > > > 
> > > > ---
> > > > 
> > > > David Lee Nidever University of Michigan, Ann Arbor
> > > > McLaughlin Fellow Department of Astronomy
> > > > dnidever@umich.edu http://www.astro.lsa.umich.edu/~dnidever
> > > > —
> > > > Reply to this email directly or view it on GitHub <
> > > > https://github.com/dnidever/PHOTRED/pull/1#issuecomment-97135230>.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/dnidever/PHOTRED/pull/1#issuecomment-97141594.
> > 
> > ## 
> > 
> > ---
> > 
> > David Lee Nidever University of Michigan, Ann Arbor
> > McLaughlin Fellow Department of Astronomy
> > dnidever@umich.edu http://www.astro.lsa.umich.edu/~dnidever
> > —
> > Reply to this email directly or view it on GitHub <
> > https://github.com/dnidever/PHOTRED/pull/1#issuecomment-97150321>.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/dnidever/PHOTRED/pull/1#issuecomment-97151085.

## 

---

David Lee Nidever              University of Michigan, Ann Arbor
McLaughlin Fellow              Department of Astronomy
dnidever@umich.edu         http://www.astro.lsa.umich.edu/~dnidever

**Comment by knutago** [comment]
I did a chown -R smash on everything, that should have done it—does it work?

**Comment by dnidever** [comment]
Yep, that worked.  Thanks.

On Tue, Apr 28, 2015 at 1:50 PM, knutago notifications@github.com wrote:

> I did a chown -R smash on everything, that should have done it—does it
> work?
> 
> > On Apr 28, 2015, at 10:47 AM, dnidever notifications@github.com wrote:
> > 
> > Can you change ownership of the files to "smash"? Some of them are "root"
> > and I can't modify them. I need to put in a stop of figure out a
> > daomaster
> > problem.
> > 
> > On Tue, Apr 28, 2015 at 1:16 PM, knutago notifications@github.com
> > wrote:
> > 
> > > Ok, have a look now, is it up to date? I had to use sudo to force a
> > > checkout to master, if your git repository is up to date it might be
> > > good
> > > to do a fresh clone as user smash...
> > > 
> > > > On Apr 28, 2015, at 9:51 AM, dnidever notifications@github.com
> > > > wrote:
> > > > 
> > > > I'm trying to copy files there by hand but I'm getting and error.
> > > > Not sure what's going on.
> > > > 
> > > > On Tue, Apr 28, 2015 at 12:46 PM, David Nidever dnidever@umich.edu
> > > > wrote:
> > > > 
> > > > > Yes. There was a crash and so I was checking/modifying things.
> > > > > I made the necessary changes on my laptop and pushed them to
> > > > > github. I was trying to update the software on "thing" when I got
> > > > > errors.
> > > > > 
> > > > > By the way, I got an error saying that "root" was full. I'm not
> > > > > sure
> > > > > what
> > > > > that's about. Do you know?
> > > > > 
> > > > > On Tue, Apr 28, 2015 at 12:01 PM, knutago <
> > > > > notifications@github.com>
> > > > > wrote:
> > > > > 
> > > > > > Hi David,
> > > > > > 
> > > > > > Just tried checking out master in the PHOTRED directory, and it’s
> > > > > > having
> > > > > > some problems. Are you fiddling with things?
> > > > > > 
> > > > > > Knut
> > > > > > 
> > > > > > > On Apr 28, 2015, at 7:39 AM, dnidever <notifications@github.com
> > > 
> > > wrote:
> > > 
> > > > > > > But now I can't update the PHOTRED code in thing from the
> > > > > > > PHOTRED
> > > > > > > repository
> > > > > > > because we are on the "knut" branch. I think we should keep the
> > > > > > > main
> > > > > > > code
> > > > > > > for
> > > > > > > thing on the "master" branch.
> > > > > > > 
> > > > > > > On Mon, Apr 27, 2015 at 2:47 PM, David Nidever <
> > > > > > > dnidever@umich.edu>
> > > > > > > wrote:
> > > > > > > 
> > > > > > > > Mine, too! It worked smoothly.
> > > > > > > > 
> > > > > > > > On Mon, Apr 27, 2015 at 2:41 PM, knutago <
> > > > > > > > notifications@github.com>
> > > > > > > > wrote:
> > > > > > > > 
> > > > > > > > > Cool, my first pull request!
> > > > > > > > > 
> > > > > > > > > > On Apr 27, 2015, at 7:14 AM, dnidever <
> > > > > > > > > > notifications@github.com>
> > > > > > > > > > wrote:
> > > > > > > > > > 
> > > > > > > > > > Merged #1 https://github.com/dnidever/PHOTRED/pull/1.
> > > > > > > > > > 
> > > > > > > > > > —
> > > > > > > > > > Reply to this email directly or view it on GitHub <
> > > > > > > > > > https://github.com/dnidever/PHOTRED/pull/1#event-290915860>.
> > > > > > > > > 
> > > > > > > > > —
> > > > > > > > > Reply to this email directly or view it on GitHub
> > > > > > > > > <
> > > > > > > > > https://github.com/dnidever/PHOTRED/pull/1#issuecomment-96775516>.
> > > > > > > > 
> > > > > > > > ## 
> > > > > > > > 
> > > > > > > > ---
> > > > > > > > 
> > > > > > > > David Lee Nidever University of Michigan, Ann Arbor
> > > > > > > > McLaughlin Fellow Department of Astronomy
> > > > > > > > dnidever@umich.edu http://www.astro.lsa.umich.edu/~dnidever
> > > > > > > 
> > > > > > > ## 
> > > > > > > 
> > > > > > > ---
> > > > > > > 
> > > > > > > David Lee Nidever University of Michigan, Ann Arbor
> > > > > > > McLaughlin Fellow Department of Astronomy
> > > > > > > dnidever@umich.edu http://www.astro.lsa.umich.edu/~dnidever
> > > > > > > —
> > > > > > > Reply to this email directly or view it on GitHub <
> > > > > > > https://github.com/dnidever/PHOTRED/pull/1#issuecomment-97087330
> > > > > > > .
> > > > > > 
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub
> > > > > > <https://github.com/dnidever/PHOTRED/pull/1#issuecomment-97118829
> > > > > > .
> > > > > 
> > > > > ## 
> > > > > 
> > > > > ---
> > > > > 
> > > > > David Lee Nidever University of Michigan, Ann Arbor
> > > > > McLaughlin Fellow Department of Astronomy
> > > > > dnidever@umich.edu http://www.astro.lsa.umich.edu/~dnidever
> > > > 
> > > > ## 
> > > > 
> > > > ---
> > > > 
> > > > David Lee Nidever University of Michigan, Ann Arbor
> > > > McLaughlin Fellow Department of Astronomy
> > > > dnidever@umich.edu http://www.astro.lsa.umich.edu/~dnidever
> > > > —
> > > > Reply to this email directly or view it on GitHub <
> > > > https://github.com/dnidever/PHOTRED/pull/1#issuecomment-97135230>.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/dnidever/PHOTRED/pull/1#issuecomment-97141594.
> > 
> > ## 
> > 
> > ---
> > 
> > David Lee Nidever University of Michigan, Ann Arbor
> > McLaughlin Fellow Department of Astronomy
> > dnidever@umich.edu http://www.astro.lsa.umich.edu/~dnidever
> > —
> > Reply to this email directly or view it on GitHub <
> > https://github.com/dnidever/PHOTRED/pull/1#issuecomment-97150321>.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/dnidever/PHOTRED/pull/1#issuecomment-97151957.

## 

---

David Lee Nidever              University of Michigan, Ann Arbor
McLaughlin Fellow              Department of Astronomy
dnidever@umich.edu         http://www.astro.lsa.umich.edu/~dnidever

**Comment by knutago** [comment]
Great

**Pull request merged**
